### ISSUE TITLE
Support of passive event listeners

### ISSUE THREAD

**Issue by sejoker** [milosjanda/react-scroll-up#13]
Lighthouse audit tools suggest implementing passive event listeners to improve scrolling performance.
From the document: https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners

> In browsers that support passive event listeners, marking a listener as passive is as easy as setting a flag:
document.addEventListener('touchstart', onTouchStart, {passive: true});
However, in browsers that do not support passive event listeners, the third parameter is a boolean to indicate whether the event should bubble or capture. So, using the syntax above may cause unintended consequences.
See the polyfill in Feature Detection to learn how to safely implement passive event listeners.

The suggested pollyfil looks like this:

```
// Test via a getter in the options object to see if the passive property is accessed
var supportsPassive = false;
try {
  var opts = Object.defineProperty({}, 'passive', {
    get: function() {
      supportsPassive = true;
    }
  });
  window.addEventListener("test", null, opts);
} catch (e) {}

// Use our detect's results. passive applied if supported, capture will be false either way.
elem.addEventListener('touchstart', fn, supportsPassive ? { passive: true } : false); 

```

I recommend adding it and ready to prepare PR.

Let me know if it will be considered useful.

**Comment by sejoker** [comment]
The browser support is quite good: http://caniuse.com/#search=passive

**Comment by milosjanda** [comment]
Hi,

thank you for suggestion, this looks useful, so i will be grateful if you send PR.
