### ISSUE TITLE
not method cancelAnimationFrame

### ISSUE THREAD

**Issue by janbaer** [milosjanda/react-scroll-up#2]
We've the problem with some android browsers, that the method cancelAnimationFrame can't be found. This browsers using the webkit engine and it's seem that their version of webkit supporting only the webkit prefixed version of this method. Could you please support it? Thanks!

**Comment by milosjanda** [comment]
Hi, how it is written in my README, if you need more compatibility, best solution is use requestAnimationFrame polyfill, like this https://gist.github.com/paulirish/1579671

**Comment by janbaer** [comment]
Thanks and sorry that I hadn't read the readme before!
