### ISSUE TITLE
React.createClass is deprecated and will be removed in version 16

### ISSUE THREAD

**Issue by finbarmaginn** [milosjanda/react-scroll-up#20]
getting following error in my console which will force me to use a different package if it is not fixed before React 16 is released

`Warning: ScrollUp: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

**Comment by milosjanda** [comment]
It should be fixed in new version v.1.2.2 by merge request https://github.com/milosjanda/react-scroll-up/pull/19
Can you confirm it?
