### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated.

### ISSUE THREAD

**Issue by finbarmaginn** [milosjanda/react-scroll-up#21]
Getting following error in my console:

`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

[https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html)

**Comment by milosjanda** [comment]
Fixed  in new verstion v1.2.3
