### ISSUE TITLE
React Peer Dependencies

### ISSUE THREAD

**Issue by eastwood** [milosjanda/react-scroll-up#25]
A recent upgrade of the peer dependencies found [here](https://github.com/milosjanda/react-scroll-up/pull/24) has broken downstream packages. While I believe the desired outcome was to support react version 0.13 -> 16.^, in fact using the semver model it has excluded all react pages.

See calculator for details https://semver.npmjs.com/

Please change peer dependencies to be expected behaviour

**Comment by milosjanda** [comment]
Thank you for nice description and contribution.
