### ISSUE TITLE
Object doesn't support property or method 'cancelAnimationFrame' 

### ISSUE THREAD

**Issue by ZeeCoder** [milosjanda/react-scroll-up#27]
I'm not sure if IE10 is a supported browser or not (I assume it is, since the readme mentions how to support even lower IE versions), but this is what I'm getting on click:
`SCRIPT438: Object doesn't support property or method 'cancelAnimationFrame' `

Great job on the lib, btw 👍

**Comment by milosjanda** [comment]
Thank you 😄 

I think when i created this library, it was works fine also under the IE10. This library use _requestAnimationFrame_ which should be supported by IE10, as documented in [Mozilla documentation](https://developer.mozilla.org/cs/docs/Web/API/Window/cancelAnimationFrame) and [Microsoft blog](https://technet.microsoft.com/cs-cz/hh920765) but not by [caniuse.com](https://caniuse.com/#search=cancelAnimationFrame) 😕 

But if the browser doesn't support _requestAnimationFrame_, you can use [requestAnimationFrame polyfill](https://gist.github.com/paulirish/1579671), which solve this problem with less effective way using _setTimeout()_ function, which is supported by all browsers.

**Comment by ZeeCoder** [comment]
Right, so just to be clear you don't plan on supporting IE10 then, and instead I should provide the polyfills then?

**Comment by milosjanda** [comment]
Exactly 👍
