### ISSUE TITLE
showUnder prop should be showOver

### ISSUE THREAD

**Issue by JustinMoser** [milosjanda/react-scroll-up#28]
Hi,
Im trying to get this button to work, but it seems to be perpetually hidden by its inline styling. I feel this is because the main prop on the component is showUnder (the number in px, and under in which to show the button). Surely it should be showOver? The button should appear after you scroll a certain amount down the page.

so it would make more sense for the prop to be showOver (ie the amount in px and over which the button should appear).

However, my button never seems to appear at all.

Thanks,
Justin

**Comment by milosjanda** [comment]
Hi,
the terminilogy doesn't matter, it depends on the point of view.
You can see a working example on the demo page https://milosjanda.github.io/react-scroll-up/ and also source code of it in branche gh-pages https://github.com/milosjanda/react-scroll-up/tree/gh-pages
I hope it will help you.
Milos
