### ISSUE TITLE
Not working inside of div with overflow-y='auto'

### ISSUE THREAD

**Issue by amir-beheshty** [milosjanda/react-scroll-up#29]
Not sure if this is an issue with the react-scroll-up container. I noticed the component will remain `hidden` no matter how far down the div I scroll down.
Example:
```
<div style={{ overflowY: 'auto' }}>
    <ScrollToTop showUnder={50}>
        <span>Up</span>
    </ScrollToTop>
</div>
```

**Comment by milosjanda** [comment]
This isn't issue, but it's feature. Library work only above the `Window` object. I think it can be done above the element with overflow property, in case of interest.
