### ISSUE TITLE
Customize button image

### ISSUE THREAD

**Issue by judygab** [milosjanda/react-scroll-up#31]
Is there a way to pass the icon for the scroll up button and not to have to choose from the three options?

**Comment by milosjanda** [comment]
I don't understand, which three options do you mean?

**Comment by judygab** [comment]
There's default button, vertical, circle arrow, and tiny up.

**Comment by milosjanda** [comment]
There is no default button. You can define whatever you want as children element. In documentation is used as for example only `<span>UP</span>`
