### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by dacevedo12** [milosjanda/react-scroll-up#34]
any plans? I'd like to contribute but I first need to know the maintainer opinion on which of the following options seems more appropriate

a. Provide the types to this repo (index.d.ts file).
b. Provide the types through https://github.com/DefinitelyTyped
c. Consider rewriting this package in TS since the codebase is small

**Comment by milosjanda** [comment]
No plans for now, but this is very nice idea and i am open to accept pull requests.
I prefer _a. Provide the types to this repo (index.d.ts file)._, because it is easy to maintenaince,

**Comment by Esot3riA** [comment]
Hello.

I'd want to use this library with Typescript, but it didn't seems to support Typescript. So I writed simple declaration file _\(index.d.ts)_.

Can I  add a pull request to support Typescript syntax?

Thank you.
Esot3riA

**Comment by milosjanda** [comment]
Hello,
Of course, I would be grateful for a pull request.
Thanks.
