### ISSUE TITLE
How to use it on React Template, Please Tell us details and clearly

### ISSUE THREAD

**Issue by salmancreation** [milosjanda/react-scroll-up#35]
Please Make a nice and details about this plugin how to use on React. 
Where i put this code or i call it ?

Thank you

**Comment by milosjanda** [comment]
Hi,
you can see working examle here https://github.com/milosjanda/react-scroll-up/blob/gh-pages/src/main.jsx that is source code of live demo https://milosjanda.github.io/react-scroll-up/
