### ISSUE TITLE
Adding onShow and onHide props

### ISSUE THREAD

**Issue by Nadav42** [milosjanda/react-scroll-up#36]
Hello, I need support for onShow and onHide props to prevent having to add extra redundant scroll listeners checking the same thing.

will you accept a pull request for this? or add it yourself?

**Comment by Nadav42** [comment]
@milosjanda

**Comment by milosjanda** [comment]
Hi, pullrequest is welcome ;)

**Comment by Nadav42** [comment]
> Hi, good point, pull request is welcome ;)

done in pull request #37

**Comment by milosjanda** [comment]
Nice work, thanks for contribution.
