### ISSUE TITLE
With React 18, type error as children are not listed as props

### ISSUE THREAD

**Issue by Codigo-Fuentes** [milosjanda/react-scroll-up#43]
Error is fixed my just adding children prop to interface `ScrollToTopProps`

<img width="1680" alt="Screen Shot 2022-04-11 at 9 48 37 AM" src="https://user-images.githubusercontent.com/43380153/162742742-440bc9c2-e129-42c7-956d-7b1a5681c668.png">

<img width="1680" alt="Screen Shot 2022-04-11 at 9 49 04 AM" src="https://user-images.githubusercontent.com/43380153/162742771-53f02069-b505-4748-8c4f-d84380aaddc1.png">

**Comment by jeffdrumgod** [comment]
Correct implement until fix component:

```typescript
import type { ScrollToTopProps as ScrollToTopPropsCustom } from 'react-scroll-up';

declare module 'react-scroll-up' {
  export interface ScrollToTopProps extends ScrollToTopPropsCustom {
    children?: React.ReactNode;
  }
}
```

**Comment by therealgilles** [comment]
I'm getting this error with the above temp fix:
```
Type 'ScrollToTopProps' recursively references itself as a base type.
```

**Comment by rgmvisser** [comment]
@therealgilles It worked for me when adding https://github.com/milosjanda/react-scroll-up/issues/43#issuecomment-1250182332 into a separate .d.ts file. Hope that helps!

**Comment by milosjanda** [comment]
Please send the pull request, because I can't simulate it and everything works for me as is.

**Comment by rgmvisser** [comment]
@milosjanda  https://github.com/milosjanda/react-scroll-up/pull/45

**Comment by milosjanda** [comment]
Sorry i missed it. It`s merged and new version has been released. Could you please confirm that everything work fine?

**Comment by rgmvisser** [comment]
Confirmed, thanks!

**Comment by milosjanda** [comment]
Thank you.
